/* Generated by the Specimen Skeleton */
export const fontData = [];
fontData.push({name:"KlarheitGrotesk-Bold",class:"klarheitgrotesk-bold"});
fontData.push({name:"KlarheitGrotesk-BoldItalic",class:"klarheitgrotesk-bolditalic"});
fontData.push({name:"KlarheitGrotesk-Book",class:"klarheitgrotesk-book"});
fontData.push({name:"KlarheitGrotesk-BookItalic",class:"klarheitgrotesk-bookitalic"});
fontData.push({name:"KlarheitGrotesk-Extrabold",class:"klarheitgrotesk-extrabold"});
fontData.push({name:"KlarheitGrotesk-ExtraboldItalic",class:"klarheitgrotesk-extrabolditalic"});
fontData.push({name:"KlarheitGrotesk-Extralight",class:"klarheitgrotesk-extralight"});
fontData.push({name:"KlarheitGrotesk-ExtralightItalic",class:"klarheitgrotesk-extralightitalic"});
fontData.push({name:"KlarheitGrotesk-Italic",class:"klarheitgrotesk-italic"});
fontData.push({name:"KlarheitGrotesk-Light",class:"klarheitgrotesk-light"});
fontData.push({name:"KlarheitGrotesk-LightItalic",class:"klarheitgrotesk-lightitalic"});
fontData.push({name:"KlarheitGrotesk-Medium",class:"klarheitgrotesk-medium"});
fontData.push({name:"KlarheitGrotesk-MediumItalic",class:"klarheitgrotesk-mediumitalic"});
fontData.push({name:"KlarheitGrotesk-Regular",class:"klarheitgrotesk-regular"});
fontData.push({name:"KlarheitGrotesk-Semibold",class:"klarheitgrotesk-semibold"});
fontData.push({name:"KlarheitGrotesk-SemiboldItalic",class:"klarheitgrotesk-semibolditalic"});
