/* Generated by the Specimen Skeleton */
export const fontData = [];
fontData.push({name:"NotoSansThai-Black",class:"notosansthai-black"});
fontData.push({name:"NotoSansThai-Bold",class:"notosansthai-bold"});
fontData.push({name:"NotoSansThai-Light",class:"notosansthai-light"});
fontData.push({name:"NotoSansThai-Medium",class:"notosansthai-medium"});
fontData.push({name:"NotoSansThai-Regular",class:"notosansthai-regular"});
fontData.push({name:"NotoSansThai-SemiBold",class:"notosansthai-semibold"});
fontData.push({name:"NotoSansThai-Thin",class:"notosansthai-thin"});
fontData.push({name:"NotoSansThaiUI-Black",class:"notosansthaiui-black"});
fontData.push({name:"NotoSansThaiUI-Bold",class:"notosansthaiui-bold"});
